name: AnvilRepair
author: VMPE Development Team
main: AnvilRepair\Main
api: [3.0.0, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.1, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13]
version: 1.1.0
description: Allows you to repair items with Anvils.
